"""Single-page PDF export of a CLERIFYMED analysis, split into small drawing helpers."""
from datetime import datetime
from io import BytesIO
from typing import Optional

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.lib.utils import simpleSplit
from reportlab.pdfgen import canvas

from models import Analysis, Report

INK = HexColor("#1C211F")
INK2 = HexColor("#5C6661")
INK3 = HexColor("#A3A8A5")
SAGE = HexColor("#5C715E")
CLAY = HexColor("#D4A373")
LINE = HexColor("#E5E2D9")
ABNORMAL = HexColor("#A84C32")
BORDERLINE = HexColor("#A8763E")
PAPER = HexColor("#F7F5F0")

STATUS_LABEL = {
    "normal": "Normal",
    "attention": "Worth reviewing",
    "urgent": "Discuss soon",
    "borderline": "Borderline",
    "abnormal": "Out of range",
    "unknown": "Not stated",
}

MARGIN = 0.85 * inch
BOTTOM = 1.05 * inch
MAX_SUMMARY_CHARS = 1250
MAX_FLAGGED_ROWS = 9
MAX_QUESTIONS = 6
MAX_RED_FLAGS = 3

DISCLAIMER = (
    "This one-page summary was generated by CLERIFYMED, an AI tool that translates medical "
    "documents into plain language for patients. It is not a diagnosis and may contain errors "
    "or omissions. Please read it alongside the original report."
)


def _format_date(iso: str) -> str:
    try:
        return datetime.fromisoformat(iso).strftime("%d %B %Y, %H:%M UTC")
    except ValueError:
        return iso


class Sheet:
    """A one-page canvas with a top-down cursor that refuses to overflow the footer."""

    def __init__(self):
        self.buffer = BytesIO()
        self.canvas = canvas.Canvas(self.buffer, pagesize=LETTER)
        self.width, self.height = LETTER
        self.right = self.width - MARGIN
        self.usable = self.right - MARGIN
        self.y = self.height - MARGIN

    @property
    def has_room(self) -> bool:
        return self.y > BOTTOM

    def room_for(self, points: float) -> bool:
        return self.y - points > BOTTOM

    def text(self, content, font, size, colour, leading_extra=3.5, indent=0.0):
        self.canvas.setFont(font, size)
        self.canvas.setFillColor(colour)
        for line in simpleSplit(content, font, size, self.usable - indent):
            if not self.has_room:
                return
            self.canvas.drawString(MARGIN + indent, self.y, line)
            self.y -= size + leading_extra

    def rule(self, colour, width, offset=9.0):
        self.canvas.setStrokeColor(colour)
        self.canvas.setLineWidth(width)
        self.canvas.line(MARGIN, self.y + offset, self.right, self.y + offset)

    def render(self) -> bytes:
        self.canvas.showPage()
        self.canvas.save()
        return self.buffer.getvalue()


def _draw_masthead(sheet: Sheet) -> None:
    c = sheet.canvas
    c.setFillColor(SAGE)
    c.roundRect(MARGIN, sheet.y - 6, 22, 22, 6, stroke=0, fill=1)
    c.setFillColor(PAPER)
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(MARGIN + 11, sheet.y + 1, "C")
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 17)
    c.drawString(MARGIN + 32, sheet.y, "CLERIFYMED")
    c.setFont("Helvetica", 8.5)
    c.setFillColor(INK3)
    c.drawRightString(sheet.right, sheet.y + 3, "Patient summary for clinical discussion")
    sheet.y -= 26
    sheet.rule(INK, 1.2, offset=0)
    sheet.y -= 24


def _draw_meta(sheet: Sheet, analysis: Analysis, report: Optional[Report]) -> None:
    doc_type = (report.document_type if report else "") or "Medical report"
    overall = STATUS_LABEL.get(report.overall_status if report else "", "—")
    sheet.text(doc_type.upper(), "Helvetica-Bold", 9, SAGE, 6)
    sheet.text((report.headline if report else "") or "Report summary", "Helvetica-Bold", 15, INK, 6)
    sheet.text(
        f"Source file: {analysis.filename}    |    Analysed: {_format_date(analysis.created_at)}"
        f"    |    Overall: {overall}",
        "Helvetica", 8.5, INK2, 8,
    )
    if analysis.patient_context:
        sheet.text(
            f"Patient-provided context: {analysis.patient_context}",
            "Helvetica-Oblique", 8.5, INK2, 8,
        )
    sheet.y -= 8


def _draw_section_title(sheet: Sheet, title: str) -> bool:
    if not sheet.room_for(26):
        return False
    sheet.rule(LINE, 0.7)
    sheet.text(title.upper(), "Helvetica-Bold", 8.5, SAGE, 7)
    return True


def _draw_summary(sheet: Sheet, report: Report) -> None:
    if not report.patient_summary or not _draw_section_title(sheet, "In plain language"):
        return
    summary = " ".join(report.patient_summary.split())
    if len(summary) > MAX_SUMMARY_CHARS:
        summary = summary[:MAX_SUMMARY_CHARS].rsplit(" ", 1)[0] + "…"
    sheet.text(summary, "Helvetica", 9.5, INK, 3.6)
    sheet.y -= 10


def _draw_flagged_values(sheet: Sheet, report: Report) -> None:
    flagged = [v for v in report.lab_values if v.status in ("abnormal", "borderline")]
    if not flagged or not _draw_section_title(sheet, "Values outside or near the edge of range"):
        return

    c = sheet.canvas
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(INK3)
    for offset, label in ((0, "TEST"), (2.55, "RESULT"), (3.75, "REFERENCE"), (5.35, "STATUS")):
        c.drawString(MARGIN + offset * inch, sheet.y, label)
    sheet.y -= 13

    for value in flagged[:MAX_FLAGGED_ROWS]:
        if not sheet.has_room:
            return
        c.setFont("Helvetica", 9)
        c.setFillColor(INK)
        c.drawString(MARGIN, sheet.y, value.name[:36])
        c.drawString(MARGIN + 2.55 * inch, sheet.y, f"{value.value} {value.unit}".strip()[:16])
        c.setFillColor(INK2)
        c.drawString(MARGIN + 3.75 * inch, sheet.y, (value.reference_range or "—")[:22])
        c.setFillColor(ABNORMAL if value.status == "abnormal" else BORDERLINE)
        c.drawString(MARGIN + 5.35 * inch, sheet.y, STATUS_LABEL.get(value.status, value.status))
        sheet.y -= 14
    sheet.y -= 6


def _draw_questions(sheet: Sheet, report: Report) -> None:
    questions = report.questions_for_doctor[:MAX_QUESTIONS]
    if not questions or not _draw_section_title(sheet, "Questions the patient would like to ask"):
        return
    for index, question in enumerate(questions, start=1):
        if not sheet.has_room:
            return
        sheet.canvas.setFont("Helvetica-Bold", 9)
        sheet.canvas.setFillColor(SAGE)
        sheet.canvas.drawString(MARGIN, sheet.y, f"{index}.")
        sheet.text(" ".join(question.split()), "Helvetica", 9.5, INK, 3.4, indent=16)
        sheet.y -= 2
    sheet.y -= 6


def _draw_red_flags(sheet: Sheet, report: Report) -> None:
    flags = report.red_flags[:MAX_RED_FLAGS]
    if not flags or not sheet.room_for(40):
        return
    if not _draw_section_title(sheet, "Flagged for prompt attention"):
        return
    for flag in flags:
        if not sheet.has_room:
            return
        sheet.text(f"— {' '.join(flag.split())}", "Helvetica", 9.5, ABNORMAL, 3.4)


def _draw_footer(sheet: Sheet) -> None:
    c = sheet.canvas
    c.setStrokeColor(LINE)
    c.setLineWidth(0.7)
    c.line(MARGIN, BOTTOM - 14, sheet.right, BOTTOM - 14)
    c.setFont("Helvetica-Bold", 7.5)
    c.setFillColor(CLAY)
    c.drawString(MARGIN, BOTTOM - 28, "NOT MEDICAL ADVICE")
    c.setFont("Helvetica", 7.5)
    c.setFillColor(INK2)
    for index, line in enumerate(simpleSplit(DISCLAIMER, "Helvetica", 7.5, sheet.usable)):
        c.drawString(MARGIN, BOTTOM - 40 - index * 9.5, line)


def build_summary_pdf(analysis: Analysis) -> bytes:
    sheet = Sheet()
    report = analysis.report
    _draw_masthead(sheet)
    _draw_meta(sheet, analysis, report)
    if report:
        _draw_summary(sheet, report)
        _draw_flagged_values(sheet, report)
        _draw_questions(sheet, report)
        _draw_red_flags(sheet, report)
    _draw_footer(sheet)
    return sheet.render()
